name: Build and Release Binaries

on:
  push:
    tags: [ 'v*' ]

env:
  GO_VERSION: '1.24'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "HYBRID"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

  build:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Set build variables
      id: vars
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          extension=".exe"
          archive_ext="zip"
        else
          extension=""
          archive_ext="tar.gz"
        fi
        echo "extension=$extension" >> $GITHUB_OUTPUT
        echo "archive_ext=$archive_ext" >> $GITHUB_OUTPUT
        echo "binary_name=formfling${extension}" >> $GITHUB_OUTPUT
        echo "archive_name=formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT

    - name: Build binary
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        go build -a -installsuffix cgo -ldflags "-s -w" -o ${{ steps.vars.outputs.binary_name }} .

    - name: Create release directory
      run: |
        mkdir -p release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
        cp ${{ steps.vars.outputs.binary_name }} release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        cp -r web/ release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        cp README.md release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        cp LICENSE release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        cp .env.example release/formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/

    - name: Create archive
      working-directory: release
      run: |
        if [ "${{ steps.vars.outputs.archive_ext }}" = "zip" ]; then
          zip -r ${{ steps.vars.outputs.archive_name }}.${{ steps.vars.outputs.archive_ext }} formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        else
          tar -czf ${{ steps.vars.outputs.archive_name }}.${{ steps.vars.outputs.archive_ext }} formfling-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}/
        fi

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/${{ steps.vars.outputs.archive_name }}.${{ steps.vars.outputs.archive_ext }}
        draft: false
        prerelease: false